Setup DynamicLinks.shorten_url and DynamicLinks::ShortenedUrl.find_or_create! alternative
saiqulhaq/dynamic_links pull request #38
Opened 2024-05-06 03:59 UTC by yosefbennywidyo

Setup ShortenedUrl Subclasses:
- create current implementation ShortenedUrl on ShortenedUrlV1
- create alternative implementation ShortenedUrl on ShortenedUrlV2

Setup DynamicLinks for current and alternative shortener:
- create DynamicLinks.ShortenerV1 for current
- create DynamicLinks.ShortenerV2 for alternative
- create shorten_url_v1 and shorten_url_v2

Create steps detail to setup benchmark

2024-05-15 15:48 UTC, saiqulhaq requested changes

2024-05-15 15:48 UTC, saiqulhaq commented on lib/dynamic_links.rb
> -  def self.shorten_url(url, client, async: DynamicLinks.configuration.async_processing)
kenapa method ini dihapus?
ini adalah method utama yg sering dipanggil oleh aplikasi yg pake gem ini

2024-05-15 15:48 UTC, saiqulhaq commented on BENCHMARKS.md
> +# Benchmark
file benchmark ini gak perlu di commit di repo
cukup di masukin deskripsi PR nya aja

jika memang V2 lebih bagus, gak perlu bikin method v2, bisa di replace shorten yg ada, biar cukup maintain 1 jenis method shorten

dan perlu dibuat juga rspec nya
percuma jika speednya bagus tp outputnya salah

2024-05-15 17:06 UTC, yosefbennywidyo commented on lib/dynamic_links.rb
> -  def self.shorten_url(url, client, async: DynamicLinks.configuration.async_processing)
agar bisa membandingkan versi yang sebelum (v1) dan sesudah (v2) perubahan, akibatnya test-nya failed.
😅

2024-05-22 12:08 UTC, saiqulhaq reviewed
code class Shortener nya kok gak ada pak?
![image](https://github.com/saiqulhaq/dynamic_links/assets/1275215/f76d5dde-3be3-49ad-ae41-63084ec60427)

apa cukup nge update validasi di model nya aja biar lebih cepet?

2024-05-22 13:45 UTC, yosefbennywidyo commented on test/lib/shortening_strategies/mock_strategy_test.rb
> +  	url = "https://example.com"
Noted

2024-05-22 13:46 UTC, yosefbennywidyo commented on test/lib/shortening_strategies/mock_strategy_test.rb
> +  	url = "https://example.com"
> indentasi

Noted

2024-05-29 14:20 UTC, yosefbennywidyo commented
> code class Shortener nya kok gak ada pak?

File ini yang dimaksud?
![Screen Shot 2024-05-29 at 22 18 17](https://github.com/saiqulhaq/dynamic_links/assets/17536001/496ee341-47f4-4988-a5af-364e740b3e58)

2024-05-29 14:27 UTC, yosefbennywidyo commented
> apa cukup nge update validasi di model nya aja biar lebih cepet?

ini salah satu alternatif, alternatif lainnya mungkin menggunakan raw SQL

2024-07-04 14:59 UTC, saiqulhaq reviewed
sorry I still don't get why by adding 
`return url_error unless url`
![image](https://github.com/saiqulhaq/dynamic_links/assets/1275215/1c806846-a98c-4d41-8d41-753f9cb2908e)

causing so much speed improvement as your benchmark result before
is it because you are testing `empty` and `exist` scenarios?

![image](https://github.com/saiqulhaq/dynamic_links/assets/1275215/177564e0-15af-41f8-b950-86bca8318d0f)

2024-07-20 18:49 UTC, yosefbennywidyo commented
> sorry I still don't get why by adding `return url_error unless url` ![image](https://private-user-images.githubusercontent.com/1275215/345875834-1c806846-a98c-4d41-8d41-753f9cb2908e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE1MDA5MDcsIm5iZiI6MTcyMTUwMDYwNywicGF0aCI6Ii8xMjc1MjE1LzM0NTg3NTgzNC0xYzgwNjg0Ni1hOThjLTRkNDEtOGQ0MS03NTNmOWNiMjkwOGUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MjBUMTgzNjQ3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDM1YTYzMTRhYmY3NjBiZDY3NDlkOGQ5N2IxMTRjOTU2YjAzNGRjY2EzMTYyNjdlYzNjNTE5Njk3MWMxYWI2NCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.ozCv6KHyjbSBoB9dNFf1AL6aYbSo8Kw8GKgK7wBI6dA)
> 
> causing so much speed improvement as your benchmark result before is it because you are testing `empty` and `exist` scenarios?
> 
> ![image](https://private-user-images.githubusercontent.com/1275215/345876765-177564e0-15af-41f8-b950-86bca8318d0f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE1MDA5MDcsIm5iZiI6MTcyMTUwMDYwNywicGF0aCI6Ii8xMjc1MjE1LzM0NTg3Njc2NS0xNzc1NjRlMC0xNWFmLTQxZjgtYjk1MC04NmJjYTgzMThkMGYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MjBUMTgzNjQ3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MmE0MGNmOWVhN2M2ZTdjZDQxMjdjMzcwNzY5Mzg2MDc0NjYwY2ExMjZmNzU2NjdlZDgzMDZjZmNmYWRmOWYyZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.F5nLhQ9KaOH5ty653IT4rnf-UI-PZJ8q4C-apHCsSNc)

My idea was to implement early exit when the url did not exist, but when I re-read the code and did a benchmark, the current code performed better.

2024-09-04 15:29 UTC, merged